version: "3"

services:
  nginx-proxy:
    build: ./
    ports:
      # web
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./html/:/usr/share/nginx/html

networks:
  default:
    name: rori-stack
