version: '3'

services:
  nginx-proxy:
    build: ./
    ports:
      # web
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./html/custom_pages:/etc/nginx/html/custom_pages

networks:
  default:
    name: rori-stack