version: "3.0"

services:
  web:
    build: ./app
    restart: always
    tty: true
    volumes:
      - ./app:/src/app
      - /var/run/docker.sock:/var/run/docker.sock
  
  nginx:
    image: nginx:alpine
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=$APP_URL

networks:
  default:
    external: true
    name: rori-stack